@startuml
'https://plantuml.com/class-diagram
set namespaceSeparator ::
class _24FSI1::String {
-str: char *
-length: int
-- Interne Methoden --
-getStringLength(NewStr: char const *): int
-{static}addiere(NewStr1: String const &, NewStr2: String const &): String
-plusGleich(NewStr: String &): String
-memZero(): void
-- Konstruktoren und Destruktoren --
+String()
+String(c: char)
+String(NewStr: char const *)
+String(NewStr: String const &)
+~String
-- Operatoren --
+operator[](i: int): char
-- Operatoren = --
+operator=(c: char): void
+operator=(NewStr: char const *): void
+operator=(NewStr: String const &): void
-- Operatoren + --
+operator+(c: char): String
+operator+(NewStr: char const *): String
+operator+(NewStr: String const &): String
-- Operatoren += --
+operator+=(c: char): String &
+operator+=(NewStr: char const *): String &
+operator+=(NewStr: String const &): String &
-- Vergleichende Operatoren --
+operator==(NewStr: String const &): bool
+operator!=(NewStr: String const &): bool
+operator<(NewStr: String const &): bool
+operator>(NewStr: String const &): bool
-- Methoden --
+Length(): int
+c_str(): char *
+toLower(): String
+toUpper(): String
+toInt(): int
-- Friends --
{friend} operator<<(std::ostream & os, String const & NewStr) : std::ostream&
{friend} operator>>(std::istream & is, String & NewStr) : std::istream&
}
}
@enduml